name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your default branch is something else

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get packages & build
      - run: flutter pub get
      - run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      # Deploy to gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/web
          publish_branch: gh-pages
          github_token: ${{ secrets.SECRET_KEY }}
